#!/bin/bash

################################################################################
# Script that warns i3wm users when the battery is low                         #
#                                                                              #
# Default Notification Thresholds:		                               #
# 1) First Notification: 20%						       #
# 2) Second Notification: 10%						       #
#                                                                              #
# Options:				                                       #
#                                                                              #
# -T : The battery value at which the first notification is sent	       #
#                                                                              #
# -t : The battery value at which the second notification is sent	       #
#                                                                              #
# -i : The path of the alert icon					       #
#                                                                              #
#                                                                              #
# By Mohammed Ayman (Oppikn), 2022                                             #
################################################################################

threshold_1=20
threshold_2=10
icon_path=

while getopts T:t:i: aflag; do
	case $aflag in
		T) threshold_1=$OPTARG;;
		t) threshold_2=$OPTARG;;
		i) icon_path=$OPTARG;;
	esac
done

# Checks wether battery is charging
isBatteryCharging() {
	battery_status="$(cat /sys/class/power_supply/BAT0/status)"
	if [ "$battery_status" == "Charging" ]; then  
	   true
	else
  	   false
	fi
}

# Returns battery capacity
getBatteryCapacity() {
	echo $(cat /sys/class/power_supply/BAT0/capacity)
}

# Sends low battery alert notification
notifyLowBattery() {
	notify-send "Low Battery Alert!" "Your Battery Level is $(getBatteryCapacity)" --icon="$icon_path"
}

# Checks wether battery is low
isBatteryLow() {
	battery_capacity=$(getBatteryCapacity)
	if (( $battery_capacity <= $threshold_1 || $battery_capacity <= $threshold_2 )); then
	    true
	else
	   false
	fi
}

if isBatteryLow && !(isBatteryCharging); then
notifyLowBattery
fi
